/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author TheSowut
 */
public class addComputerCase extends javax.swing.JFrame {

    /**
     * Creates new form addComputerCase
     */
    public addComputerCase() {
        initComponents();
        setLocationRelativeTo(null);
        final ImageIcon title = new ImageIcon(".\\images\\icons\\addComponent.png");
        final ImageIcon logoSmall = new ImageIcon(".\\images\\icons\\cpblogoSmallFull.png");
        final ImageIcon background = new ImageIcon(".\\images\\backgrounds\\addComponent.jpg");
        jLblLogo.setIcon(logoSmall);
        jLblTitle.setIcon(title);
        jLblBackground.setIcon(background);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLblTitle = new javax.swing.JLabel();
        jLblLogo = new javax.swing.JLabel();
        jLblManufacturer = new javax.swing.JLabel();
        jComboManufacturer = new javax.swing.JComboBox<>();
        jLblModel = new javax.swing.JLabel();
        jTxtModel = new javax.swing.JTextField();
        jLblType = new javax.swing.JLabel();
        jComboType = new javax.swing.JComboBox<>();
        jLblMotherboardSupport = new javax.swing.JLabel();
        jComboMotherboardSupport = new javax.swing.JComboBox<>();
        jLblExtras = new javax.swing.JLabel();
        jTxtExtras = new javax.swing.JTextField();
        jLblPrice = new javax.swing.JLabel();
        jTxtPrice = new javax.swing.JTextField();
        jBtnAdd = new javax.swing.JButton();
        jBtnBack = new javax.swing.JButton();
        jLblWarning = new javax.swing.JLabel();
        jLblBackground = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(648, 519));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(650, 510));
        jPanel1.setLayout(null);

        jLblTitle.setIcon(new javax.swing.ImageIcon("D:\\Codes\\Github\\custom-pc-builder\\images\\icons\\addComponent.png")); // NOI18N
        jPanel1.add(jLblTitle);
        jLblTitle.setBounds(130, 20, 400, 90);

        jLblLogo.setIcon(new javax.swing.ImageIcon("D:\\Codes\\Github\\custom-pc-builder\\images\\icons\\cpblogoSmallFull.png")); // NOI18N
        jPanel1.add(jLblLogo);
        jLblLogo.setBounds(440, 440, 183, 30);

        jLblManufacturer.setForeground(new java.awt.Color(255, 255, 255));
        jLblManufacturer.setText("Manufacturer:");
        jPanel1.add(jLblManufacturer);
        jLblManufacturer.setBounds(180, 130, 100, 20);

        jComboManufacturer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AOpen", "ASPEVIA", "ASRock", "Antec", "Cooler_Master", "Corsair", "Dell", "Deepcool", "EVGA", "GIGABYTE", "Lian_Li", "MSI", "NZXT", "Razer", "Rosewill" }));
        jPanel1.add(jComboManufacturer);
        jComboManufacturer.setBounds(390, 130, 100, 26);

        jLblModel.setForeground(new java.awt.Color(255, 255, 255));
        jLblModel.setText("Model:");
        jPanel1.add(jLblModel);
        jLblModel.setBounds(180, 170, 90, 20);
        jPanel1.add(jTxtModel);
        jTxtModel.setBounds(390, 170, 100, 24);

        jLblType.setForeground(new java.awt.Color(255, 255, 255));
        jLblType.setText("Type:");
        jPanel1.add(jLblType);
        jLblType.setBounds(180, 210, 80, 20);

        jComboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SSF", "Desktop", "Mini_Tower", "Mid_Tower", "Full_Tower" }));
        jPanel1.add(jComboType);
        jComboType.setBounds(390, 210, 100, 26);

        jLblMotherboardSupport.setForeground(new java.awt.Color(255, 255, 255));
        jLblMotherboardSupport.setText("Motherboard Support:");
        jPanel1.add(jLblMotherboardSupport);
        jLblMotherboardSupport.setBounds(180, 250, 130, 30);

        jComboMotherboardSupport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATX", "microATX", "miniITX", "microITX/miniITX", "ALL" }));
        jPanel1.add(jComboMotherboardSupport);
        jComboMotherboardSupport.setBounds(390, 250, 100, 26);

        jLblExtras.setForeground(new java.awt.Color(255, 255, 255));
        jLblExtras.setText("Extras:");
        jPanel1.add(jLblExtras);
        jLblExtras.setBounds(180, 290, 41, 20);
        jPanel1.add(jTxtExtras);
        jTxtExtras.setBounds(390, 290, 100, 24);

        jLblPrice.setForeground(new java.awt.Color(255, 255, 255));
        jLblPrice.setText("Price: ");
        jPanel1.add(jLblPrice);
        jLblPrice.setBounds(180, 330, 70, 30);
        jPanel1.add(jTxtPrice);
        jTxtPrice.setBounds(390, 330, 100, 24);

        jBtnAdd.setText("Add");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnAdd);
        jBtnAdd.setBounds(170, 420, 107, 32);

        jBtnBack.setText("Back");
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnBack);
        jBtnBack.setBounds(380, 420, 107, 32);

        jLblWarning.setForeground(new java.awt.Color(255, 0, 51));
        jLblWarning.setText("Please use \"_\" (underscore) instead of \" \" (space) !");
        jPanel1.add(jLblWarning);
        jLblWarning.setBounds(190, 380, 290, 16);

        jLblBackground.setIcon(new javax.swing.ImageIcon("D:\\Codes\\Github\\custom-pc-builder\\images\\backgrounds\\addComponent.jpg")); // NOI18N
        jLblBackground.setMaximumSize(new java.awt.Dimension(650, 545));
        jLblBackground.setMinimumSize(new java.awt.Dimension(650, 545));
        jPanel1.add(jLblBackground);
        jLblBackground.setBounds(0, 0, 650, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        askOnQuit.askForExit(this);
    }//GEN-LAST:event_formWindowClosing

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        // TODO add your handling code here:
        String manufacturer = jComboManufacturer.getSelectedItem().toString();
        String model = jTxtModel.getText();
        String type = jComboType.getSelectedItem().toString();
        String motherboardSupport = jComboMotherboardSupport.getSelectedItem().toString();
        String extras = jTxtExtras.getText();
        String price = jTxtPrice.getText();
        Double priceDouble = 0.0;
        
        priceDouble = Double.parseDouble(price);
        boolean validationTest = (!manufacturer.equals("") && !manufacturer.equals(" ") &&
                !model.equals("") && !model.equals(" ") && priceDouble > 0);
        
        if (validationTest){
            ArrayList<String> data = new ArrayList<String>();
            String[] columns = {"ID",
                "Manufacturer",
                "Model",
                "Type",
                "Motherboard_Support",
                "Extras",
                "Price"}; 
            computercaseConnect con = new computercaseConnect();
            con.add(columns, manufacturer, model, type, motherboardSupport, extras, priceDouble.toString());
        
            jTxtModel.setText("");
            jTxtExtras.setText("");
            jTxtPrice.setText("");
        
            JOptionPane.showMessageDialog(this, "Computer Case successfully added!", "Process Complete", 1);
            this.dispose();
            browseHardware browse = new browseHardware();
            browse.show();
        }
        else{
            JOptionPane.showMessageDialog(this, "One of the text fields is invalid !\n"
                    + "Please check your inputs.", "Invalid entry !", 0);
        }
    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        // TODO add your handling code here:
        askGoToBrowse browse = new askGoToBrowse();
        browse.goToComponents(this);
    }//GEN-LAST:event_jBtnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addComputerCase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addComputerCase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addComputerCase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addComputerCase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addComputerCase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnBack;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboManufacturer;
    private javax.swing.JComboBox<String> jComboMotherboardSupport;
    private javax.swing.JComboBox<String> jComboType;
    private javax.swing.JLabel jLblBackground;
    private javax.swing.JLabel jLblExtras;
    private javax.swing.JLabel jLblLogo;
    private javax.swing.JLabel jLblManufacturer;
    private javax.swing.JLabel jLblModel;
    private javax.swing.JLabel jLblMotherboardSupport;
    private javax.swing.JLabel jLblPrice;
    private javax.swing.JLabel jLblTitle;
    private javax.swing.JLabel jLblType;
    private javax.swing.JLabel jLblWarning;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtExtras;
    private javax.swing.JTextField jTxtModel;
    private javax.swing.JTextField jTxtPrice;
    // End of variables declaration//GEN-END:variables
}
