//  Copyright (c) 2019, Petar Gavazov(sowutmail@gmail.com)
//  Software Website: https://github.com/TheSowut/custom-pc-builder
//  All rights reserved.
//
//  Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
//
//    Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
//    Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other
//    materials provided with the distribution.
//
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
//  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
//  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
//  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
//  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

package core;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author TheSowut
 */
public class browseHardware extends javax.swing.JFrame {

    /**
     * Creates new form addNewComponent
     */
    public browseHardware() {
        initComponents();
        setLocationRelativeTo(jPanel1);
        
        final ImageIcon logoBrowse = new ImageIcon(".\\images\\icons\\browseHardware.png");
        final ImageIcon logoSmall = new ImageIcon(".\\images\\icons\\cpblogoSmallFull.png");
        final ImageIcon motherboard = new ImageIcon(".\\images\\components\\motherboard.jpg");
        final ImageIcon psu = new ImageIcon(".\\images\\components\\psu.jpg");
        final ImageIcon graphicscard = new ImageIcon(".\\images\\components\\graphicscard.jpg");
        final ImageIcon processor = new ImageIcon(".\\images\\components\\processor.jpg");
        final ImageIcon ram = new ImageIcon(".\\images\\components\\ram.jpg");
        final ImageIcon compcase = new ImageIcon(".\\images\\components\\computercase.jpg");
        final ImageIcon hdd = new ImageIcon(".\\images\\components\\hdd.jpg");
        final ImageIcon ssd = new ImageIcon(".\\images\\components\\ssd.jpg");
        final ImageIcon background = new ImageIcon(".\\images\\backgrounds\\componentsScreen.jpg");
        
        
        jLblTitle.setIcon(logoBrowse);
        jBtnMotherboard.setIcon(motherboard);
        jBtnGraphicsCard.setIcon(graphicscard);
        jBtnProcessor.setIcon(processor);
        jBtnPsu.setIcon(psu);
        jBtnRam.setIcon(ram);
        jBtnCase.setIcon(compcase);
        jBtnHdd.setIcon(hdd);
        jBtnSsd.setIcon(ssd);
        jLblLogo.setIcon(logoSmall);
        jLblBackground.setIcon(background);
    }
    
    private void goToMenu(){
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you would like to go back ?", "Exit", 2);
        if (choice == 0){
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            mainMenu menu = new mainMenu();
            menu.setVisible(true);
            this.dispose();
        }
        else {
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLblTitle = new javax.swing.JLabel();
        jBtnRam = new javax.swing.JButton();
        jBtnMotherboard = new javax.swing.JButton();
        jBtnGraphicsCard = new javax.swing.JButton();
        jBtnHdd = new javax.swing.JButton();
        jBtnProcessor = new javax.swing.JButton();
        jBtnSsd = new javax.swing.JButton();
        jLblLogo = new javax.swing.JLabel();
        jBtnBack = new javax.swing.JButton();
        jBtnPsu = new javax.swing.JButton();
        jBtnCase = new javax.swing.JButton();
        jLblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 545));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 545));
        jPanel1.setLayout(null);

        jLblTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLblTitle.setIcon(new javax.swing.ImageIcon("D:\\Codes\\Github\\custom-pc-builder\\images\\icons\\browseHardware.png")); // NOI18N
        jPanel1.add(jLblTitle);
        jLblTitle.setBounds(150, 10, 400, 120);

        jBtnRam.setIcon(new javax.swing.ImageIcon("D:\\Codes\\Github\\custom-pc-builder\\images\\components\\ram.jpg")); // NOI18N
        jBtnRam.setToolTipText("");
        jBtnRam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnRam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnRamMouseClicked(evt);
            }
        });
        jPanel1.add(jBtnRam);
        jBtnRam.setBounds(10, 310, 160, 130);

        jBtnMotherboard.setIcon(new javax.swing.ImageIcon("D:\\Codes\\Github\\custom-pc-builder\\images\\components\\motherboard.jpg")); // NOI18N
        jBtnMotherboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnMotherboard.setPreferredSize(new java.awt.Dimension(230, 141));
        jBtnMotherboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnMotherboardMouseClicked(evt);
            }
        });
        jPanel1.add(jBtnMotherboard);
        jBtnMotherboard.setBounds(10, 160, 160, 120);

        jBtnGraphicsCard.setIcon(new javax.swing.ImageIcon("D:\\Codes\\Github\\custom-pc-builder\\images\\components\\graphicscard.jpg")); // NOI18N
        jBtnGraphicsCard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnGraphicsCard.setPreferredSize(new java.awt.Dimension(230, 141));
        jBtnGraphicsCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnGraphicsCardMouseClicked(evt);
            }
        });
        jPanel1.add(jBtnGraphicsCard);
        jBtnGraphicsCard.setBounds(180, 170, 160, 120);

        jBtnHdd.setIcon(new javax.swing.ImageIcon("D:\\Codes\\Github\\custom-pc-builder\\images\\components\\hdd.jpg")); // NOI18N
        jBtnHdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnHdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnHddMouseClicked(evt);
            }
        });
        jPanel1.add(jBtnHdd);
        jBtnHdd.setBounds(350, 320, 160, 130);

        jBtnProcessor.setIcon(new javax.swing.ImageIcon("D:\\Codes\\Github\\custom-pc-builder\\images\\components\\processor.jpg")); // NOI18N
        jBtnProcessor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnProcessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnProcessorMouseClicked(evt);
            }
        });
        jBtnProcessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProcessorActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnProcessor);
        jBtnProcessor.setBounds(350, 170, 160, 120);

        jBtnSsd.setIcon(new javax.swing.ImageIcon("D:\\Codes\\Github\\custom-pc-builder\\images\\components\\ssd.jpg")); // NOI18N
        jBtnSsd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnSsd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnSsdMouseClicked(evt);
            }
        });
        jPanel1.add(jBtnSsd);
        jBtnSsd.setBounds(520, 310, 160, 130);

        jLblLogo.setIcon(new javax.swing.ImageIcon("D:\\Codes\\Github\\custom-pc-builder\\images\\icons\\cpblogoSmallFull.png")); // NOI18N
        jPanel1.add(jLblLogo);
        jLblLogo.setBounds(500, 470, 183, 35);

        jBtnBack.setText("Back");
        jBtnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnBack);
        jBtnBack.setBounds(280, 470, 125, 32);

        jBtnPsu.setIcon(new javax.swing.ImageIcon("D:\\Codes\\Github\\custom-pc-builder\\images\\components\\psu.jpg")); // NOI18N
        jBtnPsu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnPsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPsuActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnPsu);
        jBtnPsu.setBounds(520, 160, 160, 120);

        jBtnCase.setIcon(new javax.swing.ImageIcon("D:\\Codes\\Github\\custom-pc-builder\\images\\components\\computercase.jpg")); // NOI18N
        jBtnCase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCaseActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnCase);
        jBtnCase.setBounds(180, 320, 160, 130);

        jLblBackground.setIcon(new javax.swing.ImageIcon("D:\\Codes\\Github\\custom-pc-builder\\images\\backgrounds\\componentsScreen.jpg")); // NOI18N
        jPanel1.add(jLblBackground);
        jLblBackground.setBounds(0, 0, 700, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        askOnQuit.askForExit(this);
    }//GEN-LAST:event_formWindowClosing

    private void jBtnRamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRamMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "RAM");
    }//GEN-LAST:event_jBtnRamMouseClicked

    private void jBtnGraphicsCardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnGraphicsCardMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Graphics Card");
    }//GEN-LAST:event_jBtnGraphicsCardMouseClicked

    private void jBtnProcessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnProcessorMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Processor");
    }//GEN-LAST:event_jBtnProcessorMouseClicked

    private void jBtnMotherboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnMotherboardMouseClicked
        // TODO add your handling code here:
        Object[] options = {"Add",
                    "Browse",
                    "Cancel"};
        int n = JOptionPane.showOptionDialog(this, "Would you like to add or check current components of the type ?", "Add or Browse",
        JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[2]);
        if (n == 0){
            this.dispose();
            addMotherboard add = new addMotherboard();
            add.show();
        }
        else if (n == 1){
            this.dispose();
            browseMotherboard browse = new browseMotherboard();
            browse.show();
        }
        else if (n == 2){
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_jBtnMotherboardMouseClicked

    private void jBtnHddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHddMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "HDD");
    }//GEN-LAST:event_jBtnHddMouseClicked

    private void jBtnSsdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSsdMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "SSD");
    }//GEN-LAST:event_jBtnSsdMouseClicked

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        // TODO add your handling code here:
        goToMenu();
    }//GEN-LAST:event_jBtnBackActionPerformed

    private void jBtnPsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPsuActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "SSD");
    }//GEN-LAST:event_jBtnPsuActionPerformed

    private void jBtnCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCaseActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Computer Case");
    }//GEN-LAST:event_jBtnCaseActionPerformed

    private void jBtnProcessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProcessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnProcessorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(browseHardware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(browseHardware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(browseHardware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(browseHardware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new browseHardware().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBack;
    private javax.swing.JButton jBtnCase;
    private javax.swing.JButton jBtnGraphicsCard;
    private javax.swing.JButton jBtnHdd;
    private javax.swing.JButton jBtnMotherboard;
    private javax.swing.JButton jBtnProcessor;
    private javax.swing.JButton jBtnPsu;
    private javax.swing.JButton jBtnRam;
    private javax.swing.JButton jBtnSsd;
    private javax.swing.JLabel jLblBackground;
    private javax.swing.JLabel jLblLogo;
    private javax.swing.JLabel jLblTitle;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
