//  Copyright (c) 2019, Petar Gavazov(sowutmail@gmail.com)
//  Software Website: https://github.com/TheSowut/custom-pc-builder
//  All rights reserved.
//
//  Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
//
//    Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
//    Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other
//    materials provided with the distribution.
//
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
//  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
//  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
//  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
//  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

package core;

import java.awt.event.FocusEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author TheSowut
 */
public class mainMenu extends javax.swing.JFrame {

    /**
     * Creates new form mainMenu
     */
    public mainMenu() {
        initComponents();
        setLocationRelativeTo(null);
        final ImageIcon logoSmall = new ImageIcon(".\\images\\icons\\cpblogoSmallFull.png");
        final ImageIcon background = new ImageIcon(".\\images\\backgrounds\\menuBackground.jpg");
        jLblLogoSmall.setIcon(logoSmall);
        jLblBackground.setIcon(background);
        
        jLblMotherboard.hide();
        jComboMotherboards.hide();
        jLblMotherboardModel.hide();
        jComboMotherboardModels.hide();
        
        jLblGraphicsCardManufacturers.hide();
        jComboGraphicsCards.hide();
        jLblGraphicsCardsModels.hide();
        jComboGraphicsCardsModels.hide();
        
        
        jBtnNext1.hide();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLblLogoSmall = new javax.swing.JLabel();
        jLblMotherboard = new javax.swing.JLabel();
        jComboMotherboards = new javax.swing.JComboBox<>();
        jLblMotherboardModel = new javax.swing.JLabel();
        jLblGraphicsCardManufacturers = new javax.swing.JLabel();
        jComboGraphicsCards = new javax.swing.JComboBox<>();
        jLblGraphicsCardsModels = new javax.swing.JLabel();
        jComboGraphicsCardsModels = new javax.swing.JComboBox<>();
        jBtnNext1 = new javax.swing.JButton();
        jComboMotherboardModels = new javax.swing.JComboBox<>();
        jLblBackground = new javax.swing.JLabel();
        jMenu = new javax.swing.JMenuBar();
        jMenuSetups = new javax.swing.JMenu();
        jMenuSetupsCreate = new javax.swing.JMenuItem();
        jMenuSetupsBrowse = new javax.swing.JMenuItem();
        jMenuSetupsDelete = new javax.swing.JMenuItem();
        jMenuHardware = new javax.swing.JMenu();
        jMenuAbout = new javax.swing.JMenu();
        jMenuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 531));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 478));
        jPanel1.setLayout(null);

        jLblLogoSmall.setIcon(new javax.swing.ImageIcon("D:\\Codes\\Github\\custom-pc-builder\\images\\icons\\cpblogoSmallFull.png")); // NOI18N
        jLblLogoSmall.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLblLogoSmall);
        jLblLogoSmall.setBounds(500, 430, 183, 35);

        jLblMotherboard.setForeground(new java.awt.Color(255, 255, 255));
        jLblMotherboard.setText("Motherboard Manufacturer:");
        jLblMotherboard.setToolTipText("");
        jPanel1.add(jLblMotherboard);
        jLblMotherboard.setBounds(60, 40, 160, 30);

        jComboMotherboards.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboMotherboardsItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboMotherboards);
        jComboMotherboards.setBounds(50, 90, 170, 26);

        jLblMotherboardModel.setForeground(new java.awt.Color(255, 255, 255));
        jLblMotherboardModel.setText("Motherboard Model:");
        jPanel1.add(jLblMotherboardModel);
        jLblMotherboardModel.setBounds(70, 160, 120, 16);

        jLblGraphicsCardManufacturers.setForeground(new java.awt.Color(255, 255, 255));
        jLblGraphicsCardManufacturers.setText("Graphics Card Manufacturer:");
        jPanel1.add(jLblGraphicsCardManufacturers);
        jLblGraphicsCardManufacturers.setBounds(260, 120, 170, 16);

        jPanel1.add(jComboGraphicsCards);
        jComboGraphicsCards.setBounds(260, 150, 160, 26);

        jLblGraphicsCardsModels.setForeground(new java.awt.Color(255, 255, 255));
        jLblGraphicsCardsModels.setText("Graphics Card Model:");
        jPanel1.add(jLblGraphicsCardsModels);
        jLblGraphicsCardsModels.setBounds(270, 200, 130, 16);

        jPanel1.add(jComboGraphicsCardsModels);
        jComboGraphicsCardsModels.setBounds(270, 230, 120, 26);

        jBtnNext1.setText("Next");
        jBtnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNext1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnNext1);
        jBtnNext1.setBounds(310, 400, 56, 32);

        jPanel1.add(jComboMotherboardModels);
        jComboMotherboardModels.setBounds(60, 190, 140, 26);

        jLblBackground.setIcon(new javax.swing.ImageIcon("D:\\Codes\\Github\\custom-pc-builder\\images\\backgrounds\\menuBackground.jpg")); // NOI18N
        jPanel1.add(jLblBackground);
        jLblBackground.setBounds(0, 0, 700, 480);

        jMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenuSetups.setText("PC Setups");
        jMenuSetups.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuSetupsCreate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        jMenuSetupsCreate.setText("Create a new setup");
        jMenuSetupsCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuSetupsCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSetupsCreateActionPerformed(evt);
            }
        });
        jMenuSetups.add(jMenuSetupsCreate);

        jMenuSetupsBrowse.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, 0));
        jMenuSetupsBrowse.setText("Browse setups");
        jMenuSetupsBrowse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuSetupsBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSetupsBrowseActionPerformed(evt);
            }
        });
        jMenuSetups.add(jMenuSetupsBrowse);

        jMenuSetupsDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, 0));
        jMenuSetupsDelete.setText("Delete a setup");
        jMenuSetupsDelete.setContentAreaFilled(false);
        jMenuSetupsDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuSetups.add(jMenuSetupsDelete);

        jMenu.add(jMenuSetups);

        jMenuHardware.setText("Hardware");
        jMenuHardware.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuHardware.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHardwareMouseClicked(evt);
            }
        });
        jMenu.add(jMenuHardware);

        jMenuAbout.setText("About");
        jMenuAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAboutMouseClicked(evt);
            }
        });
        jMenu.add(jMenuAbout);

        jMenuHelp.setText("Help");
        jMenuHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHelpMouseClicked(evt);
            }
        });
        jMenu.add(jMenuHelp);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        askOnQuit.askForExit(this);
    }//GEN-LAST:event_formWindowClosing

    private void jMenuSetupsBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSetupsBrowseActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuSetupsBrowseActionPerformed

    private void jMenuHardwareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHardwareMouseClicked
        // TODO add your handling code here:
        this.dispose(); 
        browseHardware add = new browseHardware();
        add.setVisible(true);
    }//GEN-LAST:event_jMenuHardwareMouseClicked

    private void jMenuHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHelpMouseClicked
        // TODO add your handling code here:
        Help help = new Help();
        help.showHelp();
    }//GEN-LAST:event_jMenuHelpMouseClicked

    private void jMenuSetupsCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSetupsCreateActionPerformed
        // TODO add your handling code here:
        jLblMotherboard.show();
        jComboMotherboards.show();
        jBtnNext1.show();
        jLblGraphicsCardManufacturers.show();
        jLblGraphicsCardsModels.show();
        jComboGraphicsCards.show();
        jComboGraphicsCardsModels.show();
        
        motherboardConnect connmoth = new motherboardConnect();
        ArrayList<String> output = new ArrayList<String>();
        output = connmoth.getMotherboard("");
        for (int i = 0; i < output.size(); i++) {
            jComboMotherboards.addItem(output.get(i));
        }
        
        graphicsCardConnect conngrap = new graphicsCardConnect();
        ArrayList<String> outputGraphics = new ArrayList<String>();
        outputGraphics = conngrap.getGraphicsCard("");
        for (int i = 0; i < outputGraphics.size(); i++) {
            jComboGraphicsCards.addItem(outputGraphics.get(i));
        }
    }//GEN-LAST:event_jMenuSetupsCreateActionPerformed

    private void jMenuAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAboutMouseClicked
        // TODO add your handling code here:
        About about = new About();
        about.showAbout();
    }//GEN-LAST:event_jMenuAboutMouseClicked

    private void jComboMotherboardsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboMotherboardsItemStateChanged
        // TODO add your handling code here:
        jComboMotherboardModels.removeAllItems();
        jLblMotherboardModel.show();
        jComboMotherboardModels.show();
        String manufacturer = jComboMotherboards.getSelectedItem().toString();
        motherboardConnect connmoth = new motherboardConnect();
        ArrayList<String> output = new ArrayList<String>();
        output = connmoth.getMotherboardModel(manufacturer);
        for (int i = 0; i < output.size(); i++) {
            jComboMotherboardModels.addItem(output.get(i));
        }
    }//GEN-LAST:event_jComboMotherboardsItemStateChanged

    private void jBtnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNext1ActionPerformed
        // TODO add your handling code here:
        String chosenMotherboardManufacturer = jComboMotherboards.getSelectedItem().toString();
        String chosenMotherboardModel = jComboMotherboardModels.getSelectedItem().toString();
        String chosenMotheboard = chosenMotherboardManufacturer + " " + chosenMotherboardModel;
        
        String chosenGraphicsCardManufacturer = jComboGraphicsCards.getSelectedItem().toString();
        String chosenGraphicsCardModel = jComboGraphicsCardsModels.getSelectedItem().toString();
        String chosenGraphicsCard = chosenGraphicsCardManufacturer + " " + chosenGraphicsCardModel;
        
        
        
        
        ArrayList<String> data = new ArrayList<String>();
        createSetupConnect conn = new createSetupConnect();
        
        //data = conn.createSetup(chosenMotheboard, chosenGraphicsCard, );
        conn.close();
    }//GEN-LAST:event_jBtnNext1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-jMenuChec
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnNext1;
    private javax.swing.JComboBox<String> jComboGraphicsCards;
    private javax.swing.JComboBox<String> jComboGraphicsCardsModels;
    private javax.swing.JComboBox<String> jComboMotherboardModels;
    private javax.swing.JComboBox<String> jComboMotherboards;
    private javax.swing.JLabel jLblBackground;
    private javax.swing.JLabel jLblGraphicsCardManufacturers;
    private javax.swing.JLabel jLblGraphicsCardsModels;
    private javax.swing.JLabel jLblLogoSmall;
    private javax.swing.JLabel jLblMotherboard;
    private javax.swing.JLabel jLblMotherboardModel;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenu jMenuHardware;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenu jMenuSetups;
    private javax.swing.JMenuItem jMenuSetupsBrowse;
    private javax.swing.JMenuItem jMenuSetupsCreate;
    private javax.swing.JMenuItem jMenuSetupsDelete;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
